### ISSUE TITLE
Misnamed artifact in GHA

### ISSUE THREAD

**Issue by alanocallaghan** [qupath/log-viewer#63]
```yaml
    - uses: actions/upload-artifact@v3
      with:
        name: qupath-stardist-extension-release-jar
        path: build/libs
        retention-days: 7
```

https://github.com/qupath/log-viewer/blob/main/.github/workflows/publish-release.yml
